# Generated by Django 4.1.7 on 2023-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ussd',
            options={'verbose_name': 'User Payment Request', 'verbose_name_plural': 'User Payment Request'},
        ),
        migrations.AddField(
            model_name='ussd',
            name='status',
            field=models.CharField(choices=[('padding', 'Padding'), ('completed', 'Completed'), ('failure', 'Failure'), ('expire', 'Expire')], default='None', max_length=255),
        ),
    ]
