# Generated by Django 4.1.7 on 2023-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_alter_ussd_options_ussd_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ussd',
            options={'verbose_name': 'Payment Request', 'verbose_name_plural': 'Payment Request'},
        ),
        migrations.AlterField(
            model_name='ussd',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
